using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IDSApp.Entity
{
    /// <summary>
    /// Represents the severity level of a security alert.
    /// </summary>
    enum Severity
    {
        Low,
        Medium,
        High
    }

    /// <summary>
    /// Represents a security alert generated by the Intrusion Detection System.
    /// Contains information about detected security events, their severity, and assignment details.
    /// </summary>
    internal class Alerts
    {
        int alertId;
        int logId;
        string message;
        DateTime time;
        string status;
        Logs log;
        string attackType;
        Severity severity;
        string srcIp;
        string destIp;
        string assignedTo;

        /// <summary>Unique identifier for the alert.</summary>
        public int AlertId { get => alertId; set => alertId = value; }

        /// <summary>Reference identifier to the original log entry that triggered this alert.</summary>
        public int LogId { get => logId; set => logId = value; }

        /// <summary>Descriptive message explaining the nature of the alert.</summary>
        public string Message { get => message; set => message = value; }

        /// <summary>Timestamp when the alert was generated.</summary>
        public DateTime Time { get => time; set => time = value; }

        /// <summary>Current status of the alert (e.g., New, Investigating, Resolved).</summary>
        internal string Status { get => status; set => status = value; }

        /// <summary>Reference to the associated Logs object containing detailed log information.</summary>
        internal Logs Log { get => log; set => log = value; }

        /// <summary>Type of attack detected (e.g., DDoS, SQL Injection, Brute Force).</summary>
        public string AttackType { get => attackType; set => attackType = value; }

        /// <summary>Severity level of the alert (Low, Medium, High).</summary>
        internal Severity Severity { get => severity; set => severity = value; }

        /// <summary>Source IP address associated with the security event.</summary>
        public string SrcIp { get => srcIp; set => srcIp = value; }

        /// <summary>Destination IP address targeted by the security event.</summary>
        public string DestIp { get => destIp; set => destIp = value; }

        /// <summary>Name or identifier of the security personnel assigned to investigate this alert.</summary>
        public string AssignedTo { get => assignedTo; set => assignedTo = value; }

        /// <summary>
        /// Initializes a new instance of the Alerts class with full alert details.
        /// </summary>
        /// <param name="alertId">Unique identifier for the alert</param>
        /// <param name="logId">Reference to the original log entry</param>
        /// <param name="message">Descriptive alert message</param>
        /// <param name="time">Alert generation timestamp</param>
        /// <param name="status">Current alert status</param>
        /// <param name="log">Associated Logs object</param>
        /// <param name="attackType">Type of detected attack</param>
        /// <param name="severity">Severity level of the alert</param>
        /// <param name="srcIp">Source IP address</param>
        /// <param name="destIp">Destination IP address</param>
        /// <param name="assignedTo">Assigned security personnel</param>
        internal Alerts(int alertId, int logId, string message, DateTime time, string status, Logs log, string attackType, Severity severity, string srcIp, string destIp, string assignedTo)
        {
            this.alertId = alertId;
            this.logId = logId;
            this.message = message;
            this.time = time;
            this.status = status;
            this.log = log;
            this.attackType = attackType;
            this.severity = severity;
            this.srcIp = srcIp;
            this.destIp = destIp;
            this.assignedTo = assignedTo;
        }

        /// <summary>
        /// Initializes a new instance of the Alerts class for new alerts without log reference.
        /// Uses default values (0) for alertId and logId, and null for log parameter.
        /// </summary>
        /// <param name="message">Descriptive alert message</param>
        /// <param name="time">Alert generation timestamp</param>
        /// <param name="status">Current alert status</param>
        /// <param name="attackType">Type of detected attack</param>
        /// <param name="srcIp">Source IP address</param>
        /// <param name="destIp">Destination IP address</param>
        /// <param name="severity">Severity level of the alert</param>
        /// <param name="assignedTo">Assigned security personnel</param>
        internal Alerts(string message, DateTime time, string status, string attackType, string srcIp, string destIp, Severity severity, string assignedTo)
            : this(0, 0, message, time, status, null, attackType, severity, srcIp, destIp, assignedTo) { }

        /// <summary>
        /// Initializes a new instance of the Alerts class as a copy of an existing alert.
        /// </summary>
        /// <param name="al">Source alert object to copy from</param>
        Alerts(Alerts al)
            : this(al.alertId, al.logId, al.message, al.time, al.status, al.log, al.attackType, al.severity, al.srcIp, al.destIp, al.assignedTo) { }

        /// <summary>
        /// Creates a deep copy of the current alert instance.
        /// </summary>
        /// <returns>A new Alerts object that is a copy of the current instance</returns>
        public Alerts Clone()
        {
            return new Alerts(this);
        }
    }
}